#!/bin/bash
  
  cur_path=$(pwd)
  echo $HOME 
  echo $(pwd)
  echo $cur_path
  icount=1
  number=25
  for icount in $(seq 1 $number)
  	do
           echo $icount
           foldername=`svn list $1 | xargs -0 | sed -n "${icount},${icount+1}p"`
	   echo $foldername
	   cd $cur_path/branches/$foldername
	   svn update
        done

