#!/bin/bash
  
  cur_path=$(pwd)
  echo $cur_path
  icount=1
  number=25
  for icount in $(seq 1 $number)
  	do
           echo $icount
           foldername=`svn list $1 | xargs -0 | sed -n "${icount},${icount}p" | sed "s/\///g"`
	   if test -z $foldername ;then
	   	echo "null string"
	   else
	   	if [ -d $cur_path/branches/$foldername ] ;then
	   		echo "The folder is exist. No need to checkout again."
	   	else
			#echo "The folder is not exist. Need to checkout now."
			svn checkout $1/$foldername ./branches/$foldername
	   	fi
	    fi
        done

